name: Deploy to Remote Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: copy files via ssh key
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: ${{ secrets.TARGET_DIR }}
      - name: Migrate database
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ env.PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.TARGET_DIR }}
            source venv/bin/activate
            flask db upgrade
      - name: Restart gunicorn
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ env.PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "${{ secrets.SUDO_PASSWORD}}" | sudo -S systemctl restart flask
