name: Deploy to Remote Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy code to remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_ARGS }} 'cd ${{ secrets.TARGET_DIR }} && git pull origin main'
